### ISSUE TITLE
plot_confusion_matrix deprecated

### ISSUE THREAD

**Issue by joeldmott** [learn-co-curriculum/dsc-visualizing-confusion-matrices-lab#3]
## Link to Canvas

https://learning.flatironschool.com/courses/6536/assignments/241490?module_item_id=567725

## Issue Subtype

- [x] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
This is from the penultimate markdown cell: "Luckily, sklearn recently implemented a plot_confusion_matrix function that you can use to create a nice visual of your confusion matrices.

[Check out the documentation](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.plot_confusion_matrix.html), then visualize the confusion matrix from your logistic regression model on your test data."
```

### Concern

It's referring to a deprecated tool: plot_confusion_matrix [won't work anymore](https://scikit-learn.org/1.0/modules/generated/sklearn.metrics.plot_confusion_matrix.html), but [ConfusionMatrixDisplay's from_predictions method will.](https://scikit-learn.org/1.0/modules/generated/sklearn.metrics.ConfusionMatrixDisplay.html#sklearn.metrics.ConfusionMatrixDisplay.from_predictions)

The solution shows the right one, but the master branch doesn't. Of course, it wasn't too difficult to follow the documentation and figure it out on my own, but I thought you might want to know just in case.

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
@joeldmott Thank you for bringing this to our attention. I'll take a look and get it squared away.

**Comment by bpurdy-ds** [comment]
Thank you for pointing this out. The branches all match now.
